In [1]:
import pandas as pd
import numpy as np

In [4]:
dict_data = {
    'edad': [10,9,13,14,12,11,12],
    'cm': [115,110,130,155,125,120,125],
    'pais':['co','mx','co','mx','mx','ch','ch'],
    'genero':['M','F','F','M','M','M','F'],
    'Q1':[5,10,8,np.nan,7,8,3],
    'Q2':[7,9,9,8,8,8,9]
}

In [5]:
df = pd.DataFrame(dict_data, index= ['ana','benito','camilo','daniel','erika','fabian','gabriela'])

In [9]:
df[df['edad'] >= 12]

          edad   cm pais genero   Q1  Q2
camilo      13  130   co      F  8.0   9
daniel      14  155   mx      M  NaN   8
erika       12  125   mx      M  7.0   8
gabriela    12  125   ch      F  3.0   9

Personas mayores de 12 anios y de Mexico

In [12]:
df[(df['edad'] >= 12) & (df['pais'] == 'mx')]

        edad   cm pais genero   Q1  Q2
daniel    14  155   mx      M  NaN   8
erika     12  125   mx      M  7.0   8

In [14]:
df.query('edad > 12')

        edad   cm pais genero   Q1  Q2
camilo    13  130   co      F  8.0   9
daniel    14  155   mx      M  NaN   8

In [17]:
df[df['Q2'] >= df['Q1']]

          edad   cm pais genero   Q1  Q2
ana         10  115   co      M  5.0   7
camilo      13  130   co      F  8.0   9
erika       12  125   mx      M  7.0   8
fabian      11  120   ch      M  8.0   8
gabriela    12  125   ch      F  3.0   9

In [20]:
pd.__version__

'1.1.5'